-- Full baseline schema for chat-app (fresh installs).

CREATE TABLE IF NOT EXISTS user_accounts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(100) NOT NULL,
    password_hash   VARCHAR(100) NOT NULL,
    created_at      BIGINT       NOT NULL,
    CONSTRAINT uk_user_accounts_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS auth_sessions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(64)  NOT NULL,
    username    VARCHAR(100) NOT NULL,
    expires_at  BIGINT       NOT NULL,
    CONSTRAINT uk_auth_sessions_token UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(64)  NOT NULL,
    username    VARCHAR(100) NOT NULL,
    expires_at  BIGINT       NOT NULL,
    used        BOOLEAN      NOT NULL,
    CONSTRAINT uk_password_reset_tokens_token UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS media_assets (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name       VARCHAR(255) NOT NULL,
    content_type    VARCHAR(120) NOT NULL,
    size_bytes      BIGINT       NOT NULL,
    message_type    VARCHAR(20)  NOT NULL,
    data            BYTEA        NOT NULL,
    created_at      BIGINT       NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user           VARCHAR(100)  NOT NULL,
    to_user             VARCHAR(100)  NOT NULL,
    text                VARCHAR(2000) NOT NULL,
    message_type        VARCHAR(20)   NOT NULL DEFAULT 'TEXT',
    media_url           VARCHAR(500),
    media_content_type  VARCHAR(120),
    media_file_name     VARCHAR(255),
    timestamp           BIGINT        NOT NULL
);
