-- Phase 1 group chat: groups, membership, and group-targeted messages.

CREATE TABLE chat_groups (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(80)  NOT NULL,
    created_by   VARCHAR(40)  NOT NULL,
    created_at   BIGINT       NOT NULL
);

CREATE TABLE group_members (
    group_id     BIGINT      NOT NULL REFERENCES chat_groups (id) ON DELETE CASCADE,
    username     VARCHAR(40) NOT NULL,
    role         VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    joined_at    BIGINT      NOT NULL,
    PRIMARY KEY (group_id, username)
);

CREATE INDEX idx_group_members_username ON group_members (username);

-- DMs keep to_user set; group messages use group_id and leave to_user NULL.
ALTER TABLE chat_messages
    ALTER COLUMN to_user DROP NOT NULL;

ALTER TABLE chat_messages
    ADD COLUMN group_id BIGINT REFERENCES chat_groups (id) ON DELETE CASCADE;

CREATE INDEX idx_chat_messages_group_id ON chat_messages (group_id);
CREATE INDEX idx_chat_messages_group_timestamp ON chat_messages (group_id, timestamp);

-- Exactly one target: either a DM peer or a group (not both, not neither).
ALTER TABLE chat_messages
    ADD CONSTRAINT chk_chat_messages_target
    CHECK (
        (to_user IS NOT NULL AND group_id IS NULL)
        OR (to_user IS NULL AND group_id IS NOT NULL)
    );
